# BASE_URL = 'http://157.245.4.4:8080/'
BASE_URL = 'https://tneuron.online/'
LOGIN_END_POINT = 'auth/login/'
GET_ALL_ASSIGNED_COURSES_END_POINT = 'courses/get-all-assigned-course/'
GET_COURSE_LECTURES_END_POINT = 'courses/get-course-lectures/'